apiVersion: v1
entries:
  crossplane-service-account:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-03-09T14:42:06.736498163Z"
    description: A Helm chart for Crossplane Service Account templates
    digest: 5e356d9f516a70aa20ffccc0084585dbb1efafb50cdf44d7cd047ba6fc87a52c
    maintainers:
    - email: artur@opsguru.io
      name: artur-bolt
    name: crossplane-service-account
    sources:
    - https://github.com/upbound/provider-gcp
    - https://marketplace.upbound.io/providers
    type: application
    urls:
    - crossplane-service-account-0.0.1.tgz
    version: 0.0.1
  spark-application:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-03-09T14:42:06.737189371Z"
    description: A Helm chart for Spark Application templates
    digest: 919ca0dbf8d82d69114043e8b4f4761b15f13b1da7d392dc333924ef337a7495
    maintainers:
    - email: artur@opsguru.io
      name: artur-bolt
    name: spark-application
    sources:
    - https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/api-docs.md
    type: application
    urls:
    - spark-application-0.0.1.tgz
    version: 0.0.1
  spark-history-server:
  - apiVersion: v1
    appVersion: 2.4.0
    created: "2023-03-09T14:42:06.738527886Z"
    description: A Helm chart for Spark History Server
    digest: ed92c5c8a0bda0282f419504b21bed50bf2b106472ea8281612f8a606b5dc5fa
    home: https://spark.apache.org
    keywords:
    - spark
    - history-server
    maintainers:
    - email: artur@opsguru.io
      name: artur-bolt
    name: spark-history-server
    sources:
    - https://github.com/apache/spark
    - https://github.com/lightbend/spark-history-server-docker
    urls:
    - spark-history-server-1.0.0.tgz
    version: 1.0.0
  spark-operator:
  - apiVersion: v2
    appVersion: v1beta2-1.3.8-3.1.1
    created: "2023-03-09T14:42:06.74338454Z"
    description: A Helm chart for Spark on Kubernetes operator
    digest: 0fde4c1c5121c0902ffed9229bccdbf8c495a4a823f66c358538749b26a58b96
    home: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator
    keywords:
    - spark
    maintainers:
    - email: yuchaoran2011@gmail.com
      name: yuchaoran2011
    - email: artur@opsguru.io
      name: artur-bolt
    name: spark-operator
    urls:
    - spark-operator-1.1.26-og-0.0.2.tgz
    version: 1.1.26-og-0.0.2
  - apiVersion: v2
    appVersion: v1beta2-1.3.8-3.1.1
    created: "2023-03-09T14:42:06.740292806Z"
    description: A Helm chart for Spark on Kubernetes operator
    digest: e9f593e2577040ebec5ea1a0b19f431ef1c41a3b39c3b134db8b0da30e33edbf
    home: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator
    keywords:
    - spark
    maintainers:
    - email: yuchaoran2011@gmail.com
      name: yuchaoran2011
    - email: artur@opsguru.io
      name: artur-bolt
    name: spark-operator
    urls:
    - spark-operator-1.1.26-og-0.0.1.tgz
    version: 1.1.26-og-0.0.1
generated: "2023-03-09T14:42:06.733390128Z"
