apiVersion: v1
entries:
  crossplane-service-account:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-03-08T13:28:16.130049634Z"
    description: A Helm chart for Crossplane Service Account templates
    digest: d27c1c3655530bcd0ccf79f7e30ba2fe3215adfd475fe4c65138eea9beefb4a5
    maintainers:
    - email: artur@opsguru.io
      name: artur-bolt
    name: crossplane-service-account
    sources:
    - https://github.com/upbound/provider-gcp
    - https://marketplace.upbound.io/providers
    type: application
    urls:
    - crossplane-service-account-0.0.1.tgz
    version: 0.0.1
  spark-application:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-03-08T13:28:16.131231432Z"
    description: A Helm chart for Spark Application templates
    digest: f0e1d748e250d14aa9fcdc66733b1fe4ffb0c8b791cf0e68ad74bd832d6e689a
    maintainers:
    - email: artur@opsguru.io
      name: artur-bolt
    name: spark-application
    sources:
    - https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/api-docs.md
    type: application
    urls:
    - spark-application-0.0.1.tgz
    version: 0.0.1
  spark-history-server:
  - apiVersion: v1
    appVersion: 2.4.0
    created: "2023-03-08T13:28:16.13264683Z"
    description: A Helm chart for Spark History Server
    digest: a487893621d504c08f7cb8a0d7c70f4adff253e7af032c18b62b41801fe77d6b
    home: https://spark.apache.org
    keywords:
    - spark
    - history-server
    maintainers:
    - email: artur@opsguru.io
      name: artur-bolt
    name: spark-history-server
    sources:
    - https://github.com/apache/spark
    - https://github.com/lightbend/spark-history-server-docker
    urls:
    - spark-history-server-1.0.0.tgz
    version: 1.0.0
  spark-operator:
  - apiVersion: v2
    appVersion: v1beta2-1.3.8-3.1.1
    created: "2023-03-08T13:28:16.134468927Z"
    description: A Helm chart for Spark on Kubernetes operator
    digest: e5c4109af449fae617f45ceee5ae74b009a331a057f8a786ebd273cfb276a34c
    home: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator
    keywords:
    - spark
    maintainers:
    - email: yuchaoran2011@gmail.com
      name: yuchaoran2011
    - email: artur@opsguru.io
      name: artur-bolt
    name: spark-operator
    urls:
    - spark-operator-1.1.26-og-0.0.1.tgz
    version: 1.1.26-og-0.0.1
generated: "2023-03-08T13:28:16.128823536Z"
