{{- if eq .Values.provider "crossplane" -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "crossplane-service-account.fullname" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 15
  template:
    metadata:
      name: {{ include "crossplane-service-account.fullname" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      restartPolicy: Never
      containers:
        - name: {{ include "crossplane-service-account.fullname" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - /bin/sh
            - -c
          args:
          {{- $fullname := include "crossplane-service-account.fullname" . }}
          {{- $roles := .Values.roles }}
          {{- range $role := $roles }}
            - gcloud projects add-iam-policy-binding {{ $.Values.workloadIdentity.project }} --member=serviceAccount:{{ $fullname }}@{{ $.Values.workloadIdentity.project }}.iam.gserviceaccount.com --role {{ $role }}
          {{- end }}
          imagePullPolicy: IfNotPresent
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}