{{- if eq .Values.provider "upbound" -}}
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountIAMMember
metadata:
  annotations:
    meta.upbound.io/example-id: cloudplatform/v1beta1/serviceaccountiammember
  labels:
    crossplane.upbound.io/name: {{ include "crossplane-service-account.fullname" . }}
  name: {{ include "crossplane-service-account.fullname" . }}
spec:
  forProvider:
    member: serviceAccount:{{ .Values.workloadIdentity.project }}.svc.id.goog[{{ .Values.workloadIdentity.namespace }}/{{ .Values.workloadIdentity.serviceAccount }}]
    role: roles/iam.workloadIdentityUser
    serviceAccountIdSelector:
      matchLabels:
        crossplane.upbound.io/name: {{ include "crossplane-service-account.fullname" . }}
  deletionPolicy: {{ .Values.deletionPolicy }}
  providerConfigRef:
    name: {{ .Values.providerConfigName }}
{{- else if eq .Values.provider "crossplane" -}}
apiVersion: iam.gcp.crossplane.io/v1alpha1
kind: ServiceAccountPolicy
metadata:
  name: {{ include "crossplane-service-account.fullname" . }}
spec:
  forProvider:
    serviceAccountRef:
      name: {{ include "crossplane-service-account.fullname" . }}
    policy:
      bindings:
        - role: roles/iam.workloadIdentityUser
          members:
            - serviceAccount:{{ .Values.workloadIdentity.project }}.svc.id.goog[{{ .Values.workloadIdentity.namespace }}/{{ .Values.workloadIdentity.serviceAccount }}]
  deletionPolicy: {{ .Values.deletionPolicy }}
  providerConfigRef:
    name: {{ .Values.providerConfigName }}
{{- end }}