{{- if eq .Values.provider "crossplane" -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "crossplane-service-account.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 15
  template:
    metadata:
      name: {{ include "crossplane-service-account.fullname" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      restartPolicy: Never
      initContainers:
        - name: wait-4-crd
          image: {{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag }}
          command:
            - /bin/sh
            - -c
          args:
            - |
              while ! kubectl get serviceaccounts.iam.gcp.crossplane.io {{ include "crossplane-service-account.fullname" . }} -o=jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.status.conditions[?(@.type=="Ready")].status}{"\t"}{.status.conditions[?(@.type=="Synced")].status}{"\n"}{end}' | awk '{if ($2 == "True" && $3 == "True") print "1"; else print "0"}'; 
              do
                echo "Waiting for {{ include "crossplane-service-account.fullname" . }} to be Ready and Synced"
                sleep 2
              done
      containers:
        - name: {{ include "crossplane-service-account.fullname" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - /bin/sh
            - -c
          args:
          {{- $fullname := include "crossplane-service-account.fullname" . }}
          {{- $roles := .Values.roles }}
          {{- range $role := $roles }}
            - gcloud projects add-iam-policy-binding {{ $.Values.workloadIdentity.project }} --member=serviceAccount:{{ $fullname }}@{{ $.Values.workloadIdentity.project }}.iam.gserviceaccount.com --role {{ $role }}
          {{- end }}
          imagePullPolicy: IfNotPresent
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}