apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountIAMMember
metadata:
  annotations:
    meta.upbound.io/example-id: cloudplatform/v1beta1/serviceaccountiammember
  labels:
    crossplane.upbound.io/name: {{ include "crossplane-service-account.fullname" . }}
  name: {{ include "crossplane-service-account.fullname" . }}
spec:
  forProvider:
    member: serviceAccount:{{ .Values.workloadIdentity.project }}.svc.id.goog[{{ .Values.workloadIdentity.namespace }}/{{ .Values.workloadIdentity.serviceAccount }}]
    role: roles/iam.workloadIdentityUser
    serviceAccountIdSelector:
      matchLabels:
        crossplane.upbound.io/name: {{ include "crossplane-service-account.fullname" . }}
  deletionPolicy: {{ .Values.deletionPolicy }}
  providerConfigRef:
    name: {{ .Values.providerConfigName }}