{{- if eq .Values.provider "upbound" -}}
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  name: {{ include "crossplane-service-account.fullname" . }}
  annotations:
    meta.upbound.io/example-id: cloudplatform/v1beta1/serviceaccountiammember
  labels:
    crossplane.upbound.io/name: {{ include "crossplane-service-account.fullname" . }}
spec:
  forProvider:
    displayName: 'Crossplane ServiceAccount'
    description: 'GCP service account for {{ include "crossplane-service-account.fullname" . }}'
  deletionPolicy: {{ .Values.deletionPolicy }}
  providerConfigRef:
    name: {{ .Values.providerConfigName }}
{{- else if eq .Values.provider "crossplane" -}}
apiVersion: iam.gcp.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  name: {{ include "crossplane-service-account.fullname" . }}
spec:
  forProvider:
    displayName: 'Crossplane ServiceAccount'
    description: 'GCP service account for {{ include "crossplane-service-account.fullname" . }}'
  deletionPolicy: {{ .Values.deletionPolicy }}
  providerConfigRef:
    name: {{ .Values.providerConfigName }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.workloadIdentity.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crossplane-service-account.fullname" . }}
  namespace: {{ .Values.workloadIdentity.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ include "crossplane-service-account.fullname" . }}@{{ .Values.workloadIdentity.project }}.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "crossplane-service-account.fullname" . }}
  namespace: {{ .Values.workloadIdentity.namespace }}
rules:
- apiGroups: [""]
  resources: ["pods","services","configmaps","persistentvolumeclaims"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "crossplane-service-account.fullname" . }}
  namespace: {{ .Values.workloadIdentity.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "crossplane-service-account.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "crossplane-service-account.fullname" . }}
    namespace: {{ .Values.workloadIdentity.namespace }}
{{- end }}