{{- if eq .Values.provider "crossplane" -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "crossplane-service-account.fullname" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 15
  template:
    metadata:
      name: {{ include "crossplane-service-account.fullname" . }}
    spec:
      serviceAccountName: crossplane-system
      restartPolicy: Never
      containers:
        - name: {{ include "crossplane-service-account.fullname" . }}
          image: google/cloud-sdk:slim
          command: [ "gcloud" ]
          args: [ "projects", "add-iam-policy-binding", "{{ .Values.workloadIdentity.project }}", "--member=serviceAccount:{{ include \"crossplane-service-account.fullname\" . }}@{{ .Values.workloadIdentity.project }}.iam.gserviceaccount.com", "--role={{ .Values.role | quote }}"]
          imagePullPolicy: IfNotPresent
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}