apiVersion: v1
entries:
  spark-application:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-02-28T16:52:12.34951+01:00"
    dependencies:
    - name: spark-templates
      repository: https://raw.githubusercontent.com/ops-guru/biocatch-poc-dependencies/main/charts/
      version: 0.x.x
    description: A Helm chart for SparkApplication CRD
    digest: 94f9a345ce8318128cdbe8f1c7cd64b18c4ba297802ba28b8593ac11993395ca
    name: spark-application
    type: application
    urls:
    - spark-application-0.0.1.tgz
    version: 0.0.1
  spark-operator:
  - apiVersion: v2
    appVersion: v1beta2-1.3.8-3.1.1
    created: "2023-02-28T16:52:12.353735+01:00"
    description: A Helm chart for Spark on Kubernetes operator
    digest: 10e77e11b2ab659a931235e3ec851c7405b195843e5f233d4d775e8242ba0d8f
    home: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator
    keywords:
    - spark
    maintainers:
    - email: yuchaoran2011@gmail.com
      name: yuchaoran2011
    name: spark-operator
    urls:
    - spark-operator-1.1.26-og-0.0.1.tgz
    version: 1.1.26-og-0.0.1
  spark-templates:
  - apiVersion: v2
    created: "2023-02-28T16:52:12.354119+01:00"
    description: A Helm chart for Kubernetes templates
    digest: 2fc4308d8bfe7ebeb6c491fa3dc24b4fc4efa33f16a761185150c7eb52a8735a
    name: spark-templates
    type: library
    urls:
    - spark-templates-0.0.1.tgz
    version: 0.0.1
generated: "2023-02-28T16:52:12.348909+01:00"
