apiVersion: v2
appVersion: 1.0.0
dependencies:
  - name: spark-templates
    repository: https://raw.githubusercontent.com/ops-guru/biocatch-poc-dependencies/main/helm/packages/
    version: 0.x.x
description: A Helm chart for SparkApplication CRD
name: spark-application
type: application
version: 0.0.1
sources:
  - https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/api-docs.md
maintainers:
  - email: artur@opsguru.io
    name: artur-bolt