templateType: application
name: lifecycle-airflow-pod-operator
type: Scala
mode: cluster
image: "gcr.io/spark-operator/spark:v3.1.1"
imagePullPolicy: Always
mainClass: org.apache.spark.examples.SparkPi
mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.1.1.jar"
sparkVersion: "3.1.1"
restartPolicy:
  type: OnFailure
nodeSelector:
  kubernetes.io/arch: amd64
driver:
  cores: 1
  memory: "512m"
  labels:
    version: 3.1.1
  serviceAccount: lifecycle-airflow-dag-app-poc
  terminationGracePeriodSeconds: 60
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
executor:
  cores: 1
  memory: "512m"
  labels:
    version: 3.1.1
  serviceAccount: lifecycle-airflow-dag-app-poc
  terminationGracePeriodSeconds: 60
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
sparkConfigMap: configmap-spark-config
sparkUIOptions:
  ingressAnnotations:
    kubernetes.io/ingress.class: kong
serviceAccount:
  create: false
rbac:
  create: true
  clusterWideAccess: true
