apiVersion: v2
appVersion: 1.0.0
description: A Helm chart for Crossplane Service Account templates
name: crossplane-service-account
type: application
version: 0.0.1
sources:
  - https://github.com/upbound/provider-gcp
  - https://marketplace.upbound.io/providers
maintainers:
  - email: artur@opsguru.io
    name: artur-bolt