# -- String to partially override template (will maintain the release name)
nameOverride: ""

# -- String to override release name
fullnameOverride: ""

# -- Deletion policy for the resources
deletionPolicy: Delete

# -- Name of the Provider: upbound / crossplane
provider: crossplane

# -- Name of the Provider config
providerConfigName: ""

workloadIdentity:
  # -- Target GCP project
  project: ""
  # -- Workload identity K8s namespace
  namespace: default
  # -- Workload identity K8s service account
  serviceAccount: default

# -- Service Account role assignment
roles: []

# -- Service Account for K8s job, should have access to gcloud resources. Can be the same used by crossplane-system
serviceAccount: ""

initContainer:
  image:
    # -- Image repository for init container
    repository: bitnami/kubectl
    # -- Image tag for init container
    tag: latest

image:
  # -- Image repository
  repository: google/cloud-sdk
  # -- Image tag
  tag: slim
