name: Helm Package and Index

on:
  push:
    paths:
      - 'helm/**'

jobs:
  helm_package_and_index_library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Helm
        run: |
          wget https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
          tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
          sudo mv linux-amd64/helm /usr/local/bin/helm
          helm version

      - name: Package Helm Library Templates
        run: |
          for i in helm/templates/*/ ; do
            helm package "$i" -d helm/packages/
          done
          ls helm/packages/

      - name: Create Helm Helm Library Templates Index
        run: |
          helm repo index helm/packages/ 
          ls helm/packages/

      - name: Upload Library index.yaml
        uses: actions/upload-artifact@v2
        with:
          name: index.yaml
          path: helm/packages/index.yaml

      - name: Upload Packaged Charts
        uses: actions/upload-artifact@v2
        with:
          name: packaged-charts
          path: helm/packages/*.tgz

      - name: Commit Index
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "helm/packages/index.yaml"
          commit_message: Update Helm index.yaml
          commit_options: '--no-verify'

      - name: Commit Packages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "helm/packages/*.tgz"
          commit_message: Update Helm Packages
          commit_options: '--no-verify'

  helm_package_and_index_charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Helm
        run: |
          wget https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
          tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
          sudo mv linux-amd64/helm /usr/local/bin/helm
          helm version

      - name: Helm Update Charts Dependencies
        run:
          for i in helm/charts/*/ ; do
          helm dependency update "$i";
          done

      - name: Package Helm Charts Templates
        run: |
          for i in helm/charts/*/ ; do
            helm package "$i" -d helm/packages/
          done
          ls helm/packages/

      - name: Create Helm Charts Index
        run: |
          helm repo index helm/packages/
          ls helm/packages/

      - name: Upload index.yaml
        uses: actions/upload-artifact@v2
        with:
          name: index.yaml
          path: helm/packages/index.yaml

      - name: Upload Packaged Charts
        uses: actions/upload-artifact@v2
        with:
          name: packaged-charts
          path: helm/packages/*.tgz

      - name: Commit Index
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "helm/packages/index.yaml"
          commit_message: Update Helm index.yaml
          commit_options: '--no-verify'

      - name: Commit Packages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "helm/packages/*.tgz"
          commit_message: Update Helm Packages
          commit_options: '--no-verify'