name: Helm Package and Index

on:
  push:
    paths:
      - 'charts/**'

jobs:
  helm_package_and_index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Helm
        run: |
          wget https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
          tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
          sudo mv linux-amd64/helm /usr/local/bin/helm
          helm version

      - name: Package Helm Templates
        run: |
          helm package charts/**-templates

      - name: Helm Dependency Update
        run:
          helm dependency update charts/

      - name: Package Helm Charts
        run: |
          helm package charts/

      - name: Create Helm Repository Index
        run: |
          helm repo index charts/

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Helm charts index
          commit_options: '--no-verify'