name: Helm Package and Index

on:
  push:
    paths:
      - 'helm/**'

jobs:
  helm_package_and_index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Helm
        run: |
          wget https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
          tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
          sudo mv linux-amd64/helm /usr/local/bin/helm
          helm version

      - name: Package Helm Library Templates
        run: |
          for i in helm/templates/*/ ; do
            helm package "$i" -d helm/packages/
          done
          helm repo index helm/packages/ 

      - name: Commit Library TemplatesIndex
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "helm/packages/index.yaml"
          commit_message: Update Helm Library Templates index.yaml
          commit_options: '--no-verify'

      - name: Commit Library Templates Packages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "helm/packages/*.tgz"
          commit_message: Update Helm Library Templates Packages
          commit_options: '--no-verify'

      - name: Helm Update Charts Dependencies
        run:
          for i in helm/charts/*/ ; do
            helm dependency update "$i";
          done

      - name: Package Helm Charts Templates
        run: |
          for i in helm/charts/*/ ; do
            helm package "$i" -d helm/packages/
          done
          helm repo index helm/packages/

      - name: Commit Charts Templates Index
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "helm/packages/index.yaml"
          commit_message: Update Helm Charts Templates index.yaml
          commit_options: '--no-verify'

      - name: Commit Charts Templates Packages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "helm/packages/*.tgz"
          commit_message: Update Helm Charts Templates Packages
          commit_options: '--no-verify'

